#!/usr/bin/env bash
# Display a list of currently running processes with hierarchy in a user-oriented format

printf "%-9s %-20s %-10s %-10s %s\n" "USER" "PID" "%CPU" "%MEM" "COMMAND"

ps axo user,pid,%cpu,%mem,comm --forest --headers | head -50
