#!/usr/bin/env bash
# This script displays the username, user id, and home directory path for each user in the /etc/passwd file

while IFS=: read -r username _ uid _ home_dir _
do
    echo "$username:$uid:$home_dir"
done < /etc/passwd