#!/usr/bin/env bash
# This script tells a story based on the content of the /etc/passwd file

while IFS=: read -r username _ uid gid _ home shell
do
    userinfo=$(grep "^${uid}:" /etc/passwd)
    password=$(echo "$userinfo" | cut -d: -f2)
    useridinfo=$(echo "$userinfo" | cut -d: -f5)

    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < /etc/passwd
