#!/usr/bin/env bash
# This script tells a story based on the content of the /etc/passwd file

while IFS=: read -r username _ uid gid _ home shell
do
    group=$(getent group "$gid" | cut -d ':' -f 1)

    password="x"

    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd