#!/usr/bin/env bash
# Configures an Ubuntu server

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Update /etc/hosts file
sed -i 's/^127\.0\.0\.1[[:space:]]*localhost$/127.0.0.2 localhost/' /etc/hosts
sed -i 's/^.*\bfacebook\.com\b.*$/8.8.8.8 facebook.com/' /etc/hosts

# Flush DNS cache
if [ -x "$(command -v systemctl)" ]; then
    systemctl restart systemd-resolved
elif [ -x "$(command -v service)" ]; then
    service systemd-resolved restart
fi
