#!/usr/bin/env bash
# Configures an Ubuntu server

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
sed -i 's/^8\.8\.8\.8.*$/8.8.8.8 facebook.com/' /etc/hosts

if [ -x "$(command -v systemctl)" ]; then
    systemctl restart systemd-resolved
elif [ -x "$(command -v service)" ]; then
    service systemd-resolved restart
fi
